/**
 * Color tokens for 星璃 (StarCompanion) - 紫粉星璃品牌色
 */
import {withOpacity, stateLayerOpacity} from '../../utils/colorUtils';
import {TokenColors} from './types';

const LIGHT_PRIMARY = '#6D28D9';
const LIGHT_SECONDARY = '#DB2777';
const LIGHT_TERTIARY = '#8B5CF6';
const LIGHT_ERROR = '#EF4444';
const LIGHT_BACKGROUND = '#ffffff';
const LIGHT_ON_BACKGROUND = '#111111';
const LIGHT_SURFACE = '#F9FAFB';
const LIGHT_ON_SURFACE = '#333333';
const LIGHT_INVERSE_ON_SURFACE = '#fcfcfc';

export const lightColors: TokenColors = {
  primary: LIGHT_PRIMARY,
  onPrimary: '#FFFFFF',
  primaryContainer: '#EDE9FE',
  onPrimaryContainer: '#2D1B69',
  secondary: LIGHT_SECONDARY,
  onSecondary: '#FFFFFF',
  secondaryContainer: '#FCE7F3',
  onSecondaryContainer: '#831843',
  tertiary: LIGHT_TERTIARY,
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#F3E8FF',
  onTertiaryContainer: '#3B0764',
  error: LIGHT_ERROR,
  onError: '#FFFFFF',
  errorContainer: '#FEE2E2',
  onErrorContainer: '#7F1D1D',
  background: LIGHT_BACKGROUND,
  onBackground: LIGHT_ON_BACKGROUND,
  surface: LIGHT_SURFACE,
  onSurface: LIGHT_ON_SURFACE,
  surfaceVariant: '#e4e4e6',
  onSurfaceVariant: '#646466',
  outline: withOpacity(LIGHT_PRIMARY, 0.05),
  outlineVariant: '#a1a1a1',
  mutedLight: '#e5e3e1',
  secondaryDefault: '#f3f2f2',
  surfaceDisabled: withOpacity('#fcfcfc', 0.12),
  onSurfaceDisabled: withOpacity('#333333', 0.38),
  inverseSurface: '#858585',
  inverseOnSurface: LIGHT_INVERSE_ON_SURFACE,
  inversePrimary: '#EDE9FE',
  inverseSecondary: '#FCE7F3',
  shadow: '#000000',
  scrim: 'rgba(0, 0, 0, 0.25)',
  backdrop: 'rgba(51, 51, 51, 0.6)',
  surfaceContainerHighest: withOpacity(LIGHT_PRIMARY, 0.05),
  surfaceContainerHigh: withOpacity(LIGHT_PRIMARY, 0.03),
  surfaceContainer: withOpacity(LIGHT_PRIMARY, 0.02),
  surfaceContainerLow: withOpacity(LIGHT_PRIMARY, 0.01),
  surfaceContainerLowest: LIGHT_SURFACE,
  surfaceDim: withOpacity(LIGHT_PRIMARY, 0.06),
  surfaceBright: LIGHT_SURFACE,
  text: LIGHT_ON_BACKGROUND,
  textSecondary: withOpacity(LIGHT_ON_SURFACE, 0.5),
  inverseText: LIGHT_INVERSE_ON_SURFACE,
  inverseTextSecondary: withOpacity(LIGHT_INVERSE_ON_SURFACE, 0.5),
  border: withOpacity(LIGHT_ON_SURFACE, 0.05),
  placeholder: withOpacity(LIGHT_ON_SURFACE, 0.3),
  stateLayerOpacity: 0.12,
  hoverStateOpacity: stateLayerOpacity.hover,
  pressedStateOpacity: stateLayerOpacity.pressed,
  draggedStateOpacity: stateLayerOpacity.dragged,
  focusStateOpacity: stateLayerOpacity.focus,
  menuBackground: LIGHT_SURFACE,
  menuBackgroundDimmed: withOpacity(LIGHT_SURFACE, 0.9),
  menuBackgroundActive: withOpacity(LIGHT_PRIMARY, 0.08),
  menuSeparator: withOpacity(LIGHT_PRIMARY, 0.5),
  menuGroupSeparator: withOpacity('#000000', 0.08),
  menuText: LIGHT_ON_SURFACE,
  menuDangerText: LIGHT_ERROR,
  authorBubbleBackground: '#f5f3ff',
  receivedMessageDocumentIcon: LIGHT_PRIMARY,
  sentMessageDocumentIcon: LIGHT_ON_SURFACE,
  userAvatarImageBackground: 'transparent',
  userAvatarNameColors: [
    LIGHT_PRIMARY,
    LIGHT_SECONDARY,
    LIGHT_TERTIARY,
    LIGHT_ERROR,
  ],
  searchBarBackground: 'rgba(118, 118, 128, 0.12)',
  thinkingBubbleBackground: '#f0e6ff',
  thinkingBubbleText: '#6D28D9',
  thinkingBubbleBorder: 'rgba(109, 40, 217, 0.4)',
  thinkingBubbleShadow: '#6D28D9',
  thinkingBubbleChevronBackground: 'rgba(109, 40, 217, 0.1)',
  thinkingBubbleChevronBorder: 'rgba(109, 40, 217, 0.2)',
  bgStatusActive: '#22c55e',
  bgStatusIdle: '#d1d5db',
  btnPrimaryBg: '#f5f3ff',
  btnPrimaryBorder: '#ddd6fe',
  btnPrimaryText: '#6D28D9',
  btnReadyBg: '#f0fdf4',
  btnReadyBorder: '#bbf7d0',
  btnReadyText: '#047857',
  btnDownloadBg: '#f0fdf4',
  btnDownloadBorder: '#bbf7d0',
  btnDownloadText: '#047857',
  iconModelTypeText: '#7C3AED',
  iconModelTypeVision: '#A855F7',
  iconModelTypeAudio: '#EC4899',
  accent: {peach: '#FCE7CF', greenStrong: '#7c8e8a'},
};

const DARK_PRIMARY = '#C4B5FD';
const DARK_SECONDARY = '#F9A8D4';
const DARK_TERTIARY = '#A78BFA';
const DARK_ERROR = '#FF653F';
const DARK_BACKGROUND = '#000000';
const DARK_ON_BACKGROUND = '#ffffff';
const DARK_SURFACE = '#0E0E0E';
const DARK_ON_SURFACE = '#E2E2E2';
const DARK_INVERSE_ON_SURFACE = '#333333';

export const darkColors: TokenColors = {
  primary: DARK_PRIMARY,
  onPrimary: '#2D1B69',
  primaryContainer: '#4C1D95',
  onPrimaryContainer: '#EDE9FE',
  secondary: DARK_SECONDARY,
  onSecondary: '#831843',
  secondaryContainer: '#9D174D',
  onSecondaryContainer: '#FCE7F3',
  tertiary: DARK_TERTIARY,
  onTertiary: '#3B0764',
  tertiaryContainer: '#581C87',
  onTertiaryContainer: '#F3E8FF',
  error: DARK_ERROR,
  onError: '#4C100D',
  errorContainer: '#661511',
  onErrorContainer: '#FEE2E2',
  background: DARK_BACKGROUND,
  onBackground: DARK_ON_BACKGROUND,
  surface: DARK_SURFACE,
  onSurface: DARK_ON_SURFACE,
  surfaceVariant: '#646466',
  onSurfaceVariant: '#e3e4e6',
  outline: '#444444',
  outlineVariant: '#a1a1a1',
  mutedLight: '#3a3937',
  secondaryDefault: '#2a2928',
  surfaceDisabled: withOpacity('#333333', 0.12),
  onSurfaceDisabled: withOpacity('#e5e5e6', 0.38),
  inverseSurface: '#e5e5e6',
  inverseOnSurface: DARK_INVERSE_ON_SURFACE,
  inversePrimary: '#4C1D95',
  inverseSecondary: '#9D174D',
  shadow: '#ffffff',
  scrim: 'rgba(0, 0, 0, 0.25)',
  backdrop: 'rgba(66, 66, 66, 0.8)',
  surfaceContainerHighest: withOpacity(DARK_SURFACE, 0.22),
  surfaceContainerHigh: withOpacity(DARK_SURFACE, 0.16),
  surfaceContainer: withOpacity(DARK_SURFACE, 0.12),
  surfaceContainerLow: withOpacity(DARK_SURFACE, 0.08),
  surfaceContainerLowest: withOpacity(DARK_SURFACE, 0.04),
  surfaceDim: withOpacity(DARK_SURFACE, 0.06),
  surfaceBright: withOpacity(DARK_SURFACE, 0.24),
  text: DARK_ON_BACKGROUND,
  textSecondary: withOpacity(DARK_ON_SURFACE, 0.5),
  inverseText: DARK_INVERSE_ON_SURFACE,
  inverseTextSecondary: withOpacity(DARK_INVERSE_ON_SURFACE, 0.5),
  border: withOpacity(DARK_ON_SURFACE, 0.05),
  placeholder: withOpacity(DARK_ON_SURFACE, 0.3),
  stateLayerOpacity: 0.12,
  hoverStateOpacity: stateLayerOpacity.hover,
  pressedStateOpacity: stateLayerOpacity.pressed,
  draggedStateOpacity: stateLayerOpacity.dragged,
  focusStateOpacity: stateLayerOpacity.focus,
  menuBackground: '#2a2a2a',
  menuBackgroundDimmed: withOpacity(DARK_SURFACE, 0.9),
  menuBackgroundActive: withOpacity(DARK_PRIMARY, 0.08),
  menuSeparator: withOpacity(DARK_PRIMARY, 0.5),
  menuGroupSeparator: withOpacity('#FFFFFF', 0.08),
  menuText: DARK_ON_SURFACE,
  menuDangerText: DARK_ERROR,
  authorBubbleBackground: '#1e1b4b',
  receivedMessageDocumentIcon: DARK_PRIMARY,
  sentMessageDocumentIcon: DARK_ON_SURFACE,
  userAvatarImageBackground: 'transparent',
  userAvatarNameColors: [
    DARK_PRIMARY,
    DARK_SECONDARY,
    DARK_TERTIARY,
    DARK_ERROR,
  ],
  searchBarBackground: 'rgba(28, 28, 30, 0.92)',
  thinkingBubbleBackground: '#1e1b4b',
  thinkingBubbleText: '#C4B5FD',
  thinkingBubbleBorder: 'rgba(196, 181, 253, 0.6)',
  thinkingBubbleShadow: '#C4B5FD',
  thinkingBubbleChevronBackground: 'rgba(196, 181, 253, 0.15)',
  thinkingBubbleChevronBorder: 'rgba(196, 181, 253, 0.3)',
  bgStatusActive: '#22c55e',
  bgStatusIdle: '#4b5563',
  btnPrimaryBg: '#1e1b4b',
  btnPrimaryBorder: '#4C1D95',
  btnPrimaryText: '#C4B5FD',
  btnReadyBg: '#052e16',
  btnReadyBorder: '#166534',
  btnReadyText: '#6ee7b7',
  btnDownloadBg: '#0a1f17',
  btnDownloadBorder: '#143d2d',
  btnDownloadText: '#34d399',
  iconModelTypeText: '#C4B5FD',
  iconModelTypeVision: '#A855F7',
  iconModelTypeAudio: '#F9A8D4',
  accent: {peach: '#7A4A1F', greenStrong: '#7c8e8a'},
};
